name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for SonarCloud analysis

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=mohith140
            -Dsonar.projectKey=mohith140_SONAR_CAP
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install MTA Build Tool (mbt)
        run: |
          wget https://github.com/SAP/cloud-mta-build-tool/releases/latest/download/cloud-mta-build-tool_1.2.27_linux_amd64.tar.gz
          tar -xzf cloud-mta-build-tool_1.2.27_linux_amd64.tar.gz
          sudo mv mbt /usr/local/bin/

      - name: Run mbt build
        run: mbt build